# CSC271 Midterm Practice Problems

These problems are meant to represent the types of problems you may be asked to solve on the midterm test. They are not intended to fully cover all concepts that may be tested on the midterm. To get the most out of these problems, solve them on paper using only the provided help pages.


## Command Line & Paths

```
/ or C:\
└── Users
    └── annie
        ├── Documents
        │   ├── report.docx
        │   └── data.csv
        └── Desktop
            ├── notes.txt
            └── image.png
```

1. The current working directory is `/Users` (Mac) or `C:\Users` (Windows). Write a command to change to the `Desktop` directory using an *absolute* path.

/Users/annie/Desktop

2. The current working directory is `/Users/annie` (Mac) or `C:\Users\annie` (Windows). Write a command to change to user `annie`'s home directory using a *relative* path.

cd .. (/はあくまで何かと何かの間に入れるもの)

3. How many directories are in user `annie`'s home directory? How many files are in that directory (not including files in the subdirectories)?

2, 0

4. Briefly explain what the *root directory* is.

The root directory is the start place (/ or C:/)

## Pandas Concepts

1. A fitness tracking study records daily step counts and sleep hours. Sleep data is missing more often for participants who sleep very little, because they remove the device at night when uncomfortable.

    Is this missingness MCAR, MAR, or MNAR? Name one handling choice that would be inappropriate and explain why.

MCAR: Missing Completely at Random
MAR: Missing at Random
MNAR: Missing Not At Random

今回はMNAR. 参加者が故意にデバイスを動かしているので Not At Random

2. What is a Boolean mask, and how is it used when working with a DataFrame column (a Series)?

A Boolean mask is a Series of True and False values.

## Data Cleaning & Filtering (pandas)

The table below shows the values in a sample DataFrame, `df`. Write code below to complete the tasks described. Your code should work on any DataFrame of this format with any number of rows. You must use pandas for these tasks, not standard Python. Write expressions (not assignments) unless you are asked to modify the DataFrame/Series.


| id | name  | city      | age | score | member |
| -- | ----- | --------- | --- | ----- | ------ |
| 0  | Alice | Toronto   | 25  | 88.5  | True   |
| 1  | Bob   | Montreal  | NaN | 72.0  | False  |
| 2  | Cara  | Toronto   | 31  | 91.0  | True   |
| 3  | Dan   | Vancouver | 28  | NaN   | True   |
| 4  | Eve   | Montreal  | 25  | 88.5  | False  |
| 5  | Bob   | Montreal  | NaN | 72.0  | False  |

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'name':   ['Amina', 'Wei', 'Cara', 'Mateo', 'Eve', 'Wei'],
    'city':   ['Toronto', 'Montreal', 'Toronto', 'Vancouver', 'Montreal', 'Montreal'],
    'age':    [25, np.nan, 31, 28, 25, np.nan],
    'score':  [88.5, 72.0, 91.0, np.nan, 88.5, 72.0],
    'member': [True, False, True, True, False, False]
})

## Part A — Basic Selection & Masks

1. Produce a DataFrame with the rows of `df` where `city` is `'Toronto'`.

2. Produce a DataFrame with the rows of `df` where `age` is greater than 26.

3. Produce a DataFrame with the rows of `df` where `member` is `True`.

4. Produce a DataFrame with the rows of `df` where `score` is missing.

5. Produce a DataFrame with the rows of `df` where `city` is `'Montreal'` **and** `member` is `False`.

In [ ]:
## Part A — Basic Selection & Masks

# 1
df[df['city']=='Toronto']

# 2
df[df['age']>26]

# 3
df[df['member'] == True]

# 4
df[df['score'].isnull()]

# 5
df[(df['city'] == 'Montreal') & (df['member'] == False)]

  name      city   age  score  member
1  Wei  Montreal   NaN   72.0   False
4  Eve  Montreal  25.0   88.5   False
5  Wei  Montreal   NaN   72.0   False

---

## Part B — Column Selection + Conditions

6. Produce a DataFrame with the `name` and `score` columns for rows of `df` where `city` is `'Toronto'`.

7. Produce a Series with the `age` column for rows where `score` is at least 88.

8. Produce a DataFrame with the rows of `df` where `age` is missing or `score` is missing.

In [23]:
## Part B — Column Selection + Conditions

# 6.
df[df['city'] == 'Toronto'][['name', 'score']]

# 7.
df[df['score']>=88]['age']

# 8.
df[(df['age'].isnull()) | (df['score'].isnull())]

    name       city   age  score  member
1    Wei   Montreal   NaN   72.0   False
3  Mateo  Vancouver  28.0    NaN    True
5    Wei   Montreal   NaN   72.0   False

---

## Part C — Missing Data Handling

9. Produce a DataFrame with all rows of `df` where `age` is not missing.

10. Produce a DataFrame with all rows of `df` where neither `age` nor `score` are missing.

11. Produce a boolean mask indicating which rows of `df` have a missing `score`.

12. Get the number of missing values in the `age` column of `df`.

In [38]:
## Part C — Missing Data Handling

# 9.
df[df['age'].isnull() == False]

# 10.
df[(df['age'].isnull() == False) & (df['score'].isnull()==False)]

# 11.
df['score'].isnull()

# 12.
df['age'].isnull().sum()

np.int64(2)

---

## Part D — Duplicates
### Midterm Help Pageのdf.drop_duplicates()を参照

13. Produce a DataFrame that is the same as `df` but with duplicate rows removed, keeping the first occurrence.

14. Produce a DataFrame that is the same as `df` but with all duplicate rows removed (keep none).

In [41]:
df

    name       city   age  score  member
0  Amina    Toronto  25.0   88.5    True
1    Wei   Montreal   NaN   72.0   False
2   Cara    Toronto  31.0   91.0    True
3  Mateo  Vancouver  28.0    NaN    True
4    Eve   Montreal  25.0   88.5   False
5    Wei   Montreal   NaN   72.0   False

In [42]:
# 13.
new_df = df.drop_duplicates(keep='first')
new_df

# 14.
nodup_df = df.drop_duplicates(keep=False)
nodup_df

    name       city   age  score  member
0  Amina    Toronto  25.0   88.5    True
2   Cara    Toronto  31.0   91.0    True
3  Mateo  Vancouver  28.0    NaN    True
4    Eve   Montreal  25.0   88.5   False

---

## Part E — Combined Filtering

15. Produce a DataFrame with the rows of `df` where:

- `city` is `'Toronto'`
- `age` is at least 30
- `member` is `True`

16. Produce a DataFrame with the rows of `df` where:

- `city` is `'Montreal'`
- `score` equals 72

17. Produce a DataFrame with the rows of `df` where:

- `member` is `True`
- `score` is not missing

In [47]:
## Part E — Combined Filtering

# 15.
df[(df['city'] == 'Toronto') & (df['age'] >= 30) & (df['member'] == True)]

# 16.
df[
    (df['city'] == 'Montreal') & (df['score'] == 72)
]

# 17.
df[
    (df['member'] == True) & (df['score'].isnull() == False)
]

    name     city   age  score  member
0  Amina  Toronto  25.0   88.5    True
2   Cara  Toronto  31.0   91.0    True

---

## Part F — Code Reading

18. Give the `id`s of rows returned by:

```python
df[df['score'].isna()]
```

19. Give the `id`s of rows returned by:

```python
df[df['name'] == 'Wei']
```

20. What are the values in the `Series` produced by?

```python
df['city'].isna()
```

18. 3


19. 1, 5


20. False, False, False, False, False, False

---

## Part G — GroupBy & Transform
### dfで出したいなら：groupby().transform('mean')を忘れずに！
### Seriesならgroupby().mean()でok!
　
21. Add a column to `df` named `city_mean` that contains the **mean score within each city**.

22. Count how many people are in each city (return a Series indexed by city).

23. Compute the **median score per city** (return a Series indexed by city).

In [63]:
# 21.
df['city_mean'] = df.groupby('city')['score'].transform('mean')
df

# 22.
df['city'].value_counts()

# 23.
df.groupby('city')['score'].median()

city
Montreal     72.00
Toronto      89.75
Vancouver      NaN
Name: score, dtype: float64

---
## Part H — Plotting 

24. You want to visualize the relationship between `age` and `score` for individuals.
   **Which type of plot is most appropriate?** Briefly justify.

25. You want to compare the distribution of `score` across different `city` values.
   **Which type of plot is most appropriate?** Briefly justify.

26. You want to show how many people belong to each `city`.
   **Which type of plot is most appropriate?** Briefly justify.

24. Scatter Plot. Age and score are both numeric variables. A scatter plot shows how two numeric variables move together. It helps us see trends, patterns, and correlation.


25. Box plot. Score is numeric. City is categorical. A box plot shows the distribution of a numeric variable for each category. It helps compare median, spread, and outliers across cities.


26. Bar plot. City is categorical. We want counts. A bar plot shows the frequency of each category clearly.

## Part I - Strings Operations

27. Produce a Series of the values in the `city` column in lowercase letters.

28. Produce a DataFrame with the rows of `df` where the `name` column starts with the letter `"A"`.

29. Add a new column `name_length` to `df` containing the number of characters in each `name`.

In [5]:
df

    name       city   age  score  member
0  Amina    Toronto  25.0   88.5    True
1    Wei   Montreal   NaN   72.0   False
2   Cara    Toronto  31.0   91.0    True
3  Mateo  Vancouver  28.0    NaN    True
4    Eve   Montreal  25.0   88.5   False
5    Wei   Montreal   NaN   72.0   False

In [10]:
# 27.
df['city'].str.lower()

# 28.
df[df["name"].str.startswith("A")]

# 29.
df["name_length"] = df["name"].str.len()
df

    name       city   age  score  member  name_length
0  Amina    Toronto  25.0   88.5    True            5
1    Wei   Montreal   NaN   72.0   False            3
2   Cara    Toronto  31.0   91.0    True            4
3  Mateo  Vancouver  28.0    NaN    True            5
4    Eve   Montreal  25.0   88.5   False            3
5    Wei   Montreal   NaN   72.0   False            3

## HTML Parsing (BeautifulSoup)

Here is the HTML for a webpage about movie listings:

```html
<table class='movies'>
<tr><th>Title</th><th>Price</th></tr>
<tr><td>Movie A</td><td>$12</td></tr>
<tr><td>Movie B</td><td>$15</td></tr>
<tr><td>Movie C</td><td>$9</td></tr>
</table>
```

Complete the tasks below for HTML of the format shown above, but with any number of movies. You must use `BeautifulSoup`:

`soup = BeautifulSoup(html, "html.parser')`

1. Create a variable `first_movie` that refers to a `Tag` object representing the first row that contains movie data.

2. Create a variable `num_movies` that refers to the number of movies.


3. Complete the function below according to its docstring description.

```python
def extract_movie_titles(html: str) -> list[str]:
    """Return a list of movie titles in html.
   
    >>> extract_movie_titles(html)
    ['Movie A', 'Movie B', 'Movie C']
    """
    soup = BeautifulSoup(html, 'html.parser')
```

4. Complete the function below according to its docstring description.

```python
def build_movie_to_price(html: str) -> dict[str, int]:
    """Return a dictionary in which the keys are movie titles and the values
    are the corresponding movie prices from html.

    >>> build_movie_to_price(html)
    {'Movie A': 10, 'Movie B': 15, 'Movie C': 8}
    """
    soup = BeautifulSoup(html, 'html.parser')
```

In [25]:
#可視化するとこうなってる
pd.DataFrame(
    [['Title', 'Price'],
    ['Movie A', '$12'],
    ['Movie B', '$15'],
    ['Movie C', '$9'],
])

         0      1
0    Title  Price
1  Movie A    $12
2  Movie B    $15
3  Movie C     $9

In [35]:
from bs4 import BeautifulSoup

html = '''
<table class='movies'>
<tr><th>Title</th><th>Price</th></tr>
<tr><td>Movie A</td><td>$12</td></tr>
<tr><td>Movie B</td><td>$15</td></tr>
<tr><td>Movie C</td><td>$9</td></tr>
</table>
'''

rows = soup.find_all('tr') #listにしてtr毎に上のhtmlを並べる
td = soup.find_all('td') #listにしてtd毎で区切る

rows = rows[1:]

titles = []
for row in rows:
    cells = soup.find_all('td')
    title = cells[0].get_text()
    titles.append(title)

titles

['Movie A', 'Movie A', 'Movie A']

In [36]:
## HTML Parsing (BeautifulSoup)

from bs4 import BeautifulSoup

html = '''
<table class='movies'>
<tr><th>Title</th><th>Price</th></tr>
<tr><td>Movie A</td><td>$12</td></tr>
<tr><td>Movie B</td><td>$15</td></tr>
<tr><td>Movie C</td><td>$9</td></tr>
</table>
'''

# 1. Movie Aだけとる (tr = table row, th = table header)
soup = BeautifulSoup(html, 'html.parser')
first_movie = soup.find_all('tr')[1] 


# 2.
soup = BeautifulSoup(html, 'html.parser')
num_movies = len(soup.find_all('tr')[1:])
num_movies

# 3. 

def extract_movie_titles(html: str) -> list[str]:
    """Return a list of movie titles in html.
   
    >>> extract_movie_titles(html)
    ['Movie A', 'Movie B', 'Movie C']
    """

    soup = BeautifulSoup(html, 'html.parser')
    
    titles = []
    rows = soup.find_all('tr')
    rows = rows[1:]

    for row in rows:
        cells = row.find_all('td')
        title = cells[0].get_text()
        titles.append(title)
    
    return titles

# 4. 

def build_movie_to_price(html: str) -> dict[str, int]:
    """Return a dictionary in which the keys are movie titles and the values
    are the corresponding movie prices from html.

    >>> build_movie_to_price(html)
    {'Movie A': 12, 'Movie B': 15, 'Movie C': 9}
    """

    soup = BeautifulSoup(html, 'html.parser')
    result = {}

    rows = soup.find_all('tr')

    for row in rows:
        cells = soup.find_all('td')
        title = cells[0].get_text()
        price = cells[1].get_text()
        price = int(price_text[1:])
        result[title] = price
    


import doctest
doctest.testmod()

**********************************************************************
File "__main__", line 52, in __main__.build_movie_to_price
Failed example:
    build_movie_to_price(html)
Exception raised:
    Traceback (most recent call last):
      File "/opt/miniconda3/lib/python3.13/doctest.py", line 1398, in __run
        exec(compile(example.source, filename, "single",
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                     compileflags, True), test.globs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<doctest __main__.build_movie_to_price[0]>", line 1, in <module>
        build_movie_to_price(html)
        ~~~~~~~~~~~~~~~~~~~~^^^^^^
      File "/var/folders/8b/l3hn2xz95s339fcjyn4t7t8r0000gn/T/ipykernel_19092/2113910559.py", line 65, in build_movie_to_price
        price = int(price_text[1:])
                    ^^^^^^^^^^
    NameError: name 'price_text' is not defined
**********************************************************************
1 item had failures:
   1 of   1 in __main__.build_movie_to_price
***Test Failed*** 1 failure.

TestResults(failed=1, attempted=2)

## Regular Expressions

1. List all strings that fully match the regular expression: `[A-Z]{2}\d`.

2. Write a regular expression that matches a 3-digit number.

3. Split a string `s` on comma or semicolon (e.g., `'cat,dog;bird'` becomes `['cat', dog', 'bird']`).

4. Complete the function below according to its docstring description. You must use the `re` module.

    ```python3
    import re

    def replace_extension(filename: str) -> str:
        """Return filename with its extension replaced by '.txt'.

        Precondtion: filename has the form: name.ext, where ext contains 3 letters

        >>> replace_extension('report.pdf')
        'report.txt'
        >>> replace_extension('data.csv')
        'data.txt'
        """
    ```

5. Complete the function below according to its docstring description. You must use the `re` module.

    ```python3
    import re

    def reformat_date(date_str: str) -> str:
        """Return date_str converted from YYYY-MM-DD format to DD/MM/YYYY.

        >>> reformat_date('2025-03-08')
        '08/03/2025'
        >>> reformat_date('1999-12-31')
        '31/12/1999'
        """
    ```

## Regular Expressions

1.

In [ ]:
import re

# 2. 


# 3. 

# 4. 

import re

def replace_extension(filename: str) -> str:
    """Return filename with its extension replaced by '.txt'.

    Precondtion: filename has the form: name.ext, where ext contains 3 letters

    >>> replace_extension('report.pdf')
    'report.txt'
    >>> replace_extension('data.csv')
    'data.txt'
    """
    return re.sub(r'\.[A-Za-z]{3}', '.txt', filename)


# 5. 

import re

def reformat_date(date_str: str) -> str:
    """Return date_str converted from YYYY-MM-DD format to DD/MM/YYYY.

    >>> reformat_date('2025-03-08')
    '08/03/2025'
    >>> reformat_date('1999-12-31')
    '31/12/1999'
    """
    
    return re.sub(r'(\d{4})-(\d{2})-(\d{2})', r'\3/\2/\1', date_str)

import doctest
doctest.testmod()